spring:
  application:
    name: Sharian

  datasource:
    url: jdbc:postgresql://localhost:5432/sharian_db
    username: postgres
    password: 1234


  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true


jwt:
  secret: SharyanSecretKeyForJwtAuthenticationSystem123456789
  expiration: 86400000